import type { Room } from "../../../types";

export const rooms: Room[] = [
  {
    id: "ci-219",
    location: "CI 219",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["ruy-alberto-pisani-altafim", "mardson-freitas-de-amorim", "henrique"],
  },
  {
    id: "ci-220",
    location: "CI 220",
    type: "professor-office",
    description: "Sala de Professor",
    professors: [
      "gledson-elias-da-silveira",
      "gustavo-henrique-matos-bezerra-motta",
      "natasha-correia-queiroz-lino",
    ],
  },
  {
    id: "ci-221",
    location: "CI 221",
    type: "professor-office",
    description: "Sala de Professor",
    professors: [
      "jose-antonio-gomes-de-lima",
      "vitor-meneghetti-ugulino-de-araujo",
      "alan-kelon-oliveira-de-moraes",
    ],
  },
  {
    id: "ci-222",
    location: "CI 222",
    type: "professor-office",
    description: "Sala de Professor",
    professors: [
      "roberto-quirino-do-nascimento",
      "moises-dantas-dos-santos",
      "aparecido-jesuino-de-souza",
    ],
  },
  {
    id: "ci-223",
    location: "CI 223",
    type: "professor-office",
    description: "Sala de Professor",
    professors: [
      "lucidio-dos-anjos-formiga-cabral",
      "bruno-jefferson-de-sousa-pessoa",
      "gilberto-farias-de-sousa-filho",
    ],
  },
  {
    id: "ci-224",
    location: "CI 224",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["derzu-omaia", "leonardo-vidal-batista", "hugo-leonardo-davi-de-souza-cavalcante"],
  },
  {
    id: "ci-225",
    location: "CI 225",
    type: "professor-office",
    description: "Sala de Professor",
    professors: [
      "carlos-eduardo-coelho-freire-batista",
      "leandro-carlos-de-souza",
      "valdecir-becker",
    ],
  },
  {
    id: "ci-226",
    location: "CI 226",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["danielle-rousy-dias-ricarte", "fernando-menezes-matos", "marcelo-yuri"],
  },
  {
    id: "ci-227",
    location: "CI 227",
    type: "professor-office",
    description: "Sala de Professor. Também pertence ao MCC (Meninas na Ciência da Computação)",
    professors: [
      "mcc-meninas-na-ciencia-da-computacao",
      "josilene-aires-moreira",
      "giorgia-de-oliveira-mattos",
    ],
  },
  {
    id: "corredor",
    location: "Corredor",
    type: "corridor",
    description: "Corredor",
  },
  {
    id: "banheiro-feminino",
    location: "Banheiro Feminino",
    type: "bathroom",
    description: "Banheiro Feminino",
    gender: "female",
  },
  {
    id: "banheiro-masculino",
    location: "Banheiro Masculino",
    type: "bathroom",
    description: "Banheiro Masculino",
    gender: "male",
  },
  {
    id: "ci-209",
    location: "CI 209",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["raimundo"],
  },
  {
    id: "ci-210",
    location: "CI 210",
    type: "professor-office",
    description: "Sala de Professor",
    professors: [],
  },
  {
    id: "ci-208",
    location: "CI 208",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["gustavo-charles-peixoto-de-oliveira", "tatiana-araujo-simoes"],
  },
  {
    id: "ci-211",
    location: "CI 211",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["yuska-paola-costa-aguiar", "lincoln-david-nery-e-silva"],
  },
  {
    id: "ci-207",
    location: "CI 207",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["jairo-rocha-de-faria", "sergio-de-carvalho-bezerra"],
  },
  {
    id: "ci-212",
    location: "CI 212",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["rostand", "raoni-kulesza"],
  },
  {
    id: "ci-206",
    location: "CI 206",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["clauirton-de-albuquerque-siebra", "francisco-de-assis-coutinho-souto"],
  },
  {
    id: "ci-213",
    location: "CI 213",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["ed-porto-bezerra", "liliane-dos-santos-machado"],
  },
  {
    id: "ci-205",
    location: "CI 205",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["teobaldo-leite-bulhoes-junior"],
  },
  {
    id: "ci-214",
    location: "CI 214",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["bruno-petrato-bruck"],
  },
  {
    id: "ci-204",
    location: "CI 204",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["andrei-de-araujo-formiga"],
  },
  {
    id: "ci-215",
    location: "CI 215",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["elizabet-maria-spohr-de-medeiros", "alvaro-francisco-de-castro-medeiros"],
  },
  {
    id: "ci-203",
    location: "CI 203",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["antonio-jose-boness-dos-santos", "ana-paula-pintado-wyse"],
  },
  {
    id: "ci-216",
    location: "CI 216",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["jose-miguel-aroztegui-massera"],
  },
  {
    id: "ci-202",
    location: "CI 202",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["daniela-coelho-batista-guedes-pereira", "thais-gaudencio-do-rego"],
  },
  {
    id: "ci-217",
    location: "CI 217",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["iguatemi-eduardo-da-fonseca", "anand-subramanian"],
  },
  {
    id: "ci-201",
    location: "CI 201",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["camila-mara-vital-barros", "luciano-sales-barros"],
  },
  {
    id: "ci-218",
    location: "CI 218",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["kely-diana-villacorta-villacorta", "felipe-antonio-garcia-moreno"],
  },
];
