import type { Room } from "../../../types";

export const rooms: Room[] = [
  {
    id: "ci-219",
    location: "CI 219",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Ruy", "Mardson", "Henrique"],
  },
  {
    id: "ci-220",
    location: "CI 220",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Gledson Elias", "Gustavo Motta", "Natasha Queiroz"],
  },
  {
    id: "ci-221",
    location: "CI 221",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["José Antonio", "Vitor", "Alan"],
  },
  {
    id: "ci-222",
    location: "CI 222",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Roberto Quirino", "Moisés Dantas", "Aparecida de Souza"],
  },
  {
    id: "ci-223",
    location: "CI 223",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Lucídio Cabral", "Bruno Pessoa", "Gilberto Farias"],
  },
  {
    id: "ci-224",
    location: "CI 224",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Derzu Omaia", "Leonardo Vidal", "Hugo Leonardo"],
  },
  {
    id: "ci-225",
    location: "CI 225",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Bidu", "Leandro", "Valdecir"],
  },
  {
    id: "ci-226",
    location: "CI 226",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Danielle Rousy", "Fernando Matos", "Marcelo Yuri"],
  },
  {
    id: "ci-227",
    location: "CI 227",
    type: "professor-office",
    description: "Sala de Professor. Também pertence ao MCC (Meninas na Ciência da Computação)",
    professors: ["MCC", "Josilene Aires", "Giorgia Mattos"],
  },
  {
    id: "corredor",
    location: "Corredor",
    type: "corridor",
    description: "Corredor",
  },
  {
    id: "banheiro-feminino",
    location: "Banheiro Feminino",
    type: "bathroom",
    description: "Banheiro Feminino",
    gender: "female",
  },
  {
    id: "banheiro-masculino",
    location: "Banheiro Masculino",
    type: "bathroom",
    description: "Banheiro Masculino",
    gender: "male",
  },
  {
    id: "ci-209",
    location: "CI 209",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Raimundo"],
  },
  {
    id: "ci-210",
    location: "CI 210",
    type: "professor-office",
    description: "Sala de Professor",
    professors: [],
  },
  {
    id: "ci-208",
    location: "CI 208",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Gustavo Peixoto", "Tatiana Araújo"],
  },
  {
    id: "ci-211",
    location: "CI 211",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Yuska", "Lincoln"],
  },
  {
    id: "ci-207",
    location: "CI 207",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Jairo", "Sérgio"],
  },
  {
    id: "ci-212",
    location: "CI 212",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Rostand", "Raoni"],
  },
  {
    id: "ci-206",
    location: "CI 206",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Clauirton", "Coutinho"],
  },
  {
    id: "ci-213",
    location: "CI 213",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Ed Porto", "Liliane"],
  },
  {
    id: "ci-205",
    location: "CI 205",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Teobaldo"],
  },
  {
    id: "ci-214",
    location: "CI 214",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Bruno Bruck"],
  },
  {
    id: "ci-204",
    location: "CI 204",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Andrei"],
  },
  {
    id: "ci-215",
    location: "CI 215",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Elizabet Spohr", "Álvaro Medeiros"],
  },
  {
    id: "ci-203",
    location: "CI 203",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Boness", "Ana Paula"],
  },
  {
    id: "ci-216",
    location: "CI 216",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Miguel Aroztegui"],
  },
  {
    id: "ci-202",
    location: "CI 202",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Daniela", "Thaís"],
  },
  {
    id: "ci-217",
    location: "CI 217",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Iguatemi", "Anand"],
  },
  {
    id: "ci-201",
    location: "CI 201",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Camila", "Luciano"],
  },
  {
    id: "ci-218",
    location: "CI 218",
    type: "professor-office",
    description: "Sala de Professor",
    professors: ["Kely", "Felipe"],
  },
];
