import type { Room } from "../../../types";

export const rooms: Room[] = [
  {
    id: "ci-312",
    location: "CI 312",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["lmi"],
  },
  {
    id: "ci-313",
    location: "CI 313",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["compose", "lia", "dat", "avis", "laqss"],
  },
  {
    id: "ci-314",
    location: "CI 314",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["zoox-smart-data"],
  },
  {
    id: "ci-315",
    location: "CI 315",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["tril"],
  },
  {
    id: "ci-316",
    location: "CI 316",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["laporte"],
  },
  {
    id: "ci-317",
    location: "CI 317",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["lar"],
  },
  {
    id: "ci-318",
    location: "CI 318",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["lumo"],
  },
  {
    id: "ci-319",
    location: "CI 319",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["lim"],
  },
  {
    id: "ci-320",
    location: "CI 320",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["lasid"],
  },
  {
    id: "corredor",
    location: "Corredor",
    type: "corridor",
    description: "Corredor",
  },
  {
    id: "banheiro-feminino",
    location: "Banheiro Feminino",
    type: "bathroom",
    description: "Banheiro Feminino",
    gender: "female",
  },
  {
    id: "banheiro-masculino",
    location: "Banheiro Masculino",
    type: "bathroom",
    description: "Banheiro Masculino",
    gender: "male",
  },
  {
    id: "ci-311",
    location: "CI 311",
    type: "classroom",
    description: "Sala de aula CI 311",
  },
  {
    id: "ci-310",
    location: "CI 310",
    type: "classroom",
    description: "Sala de aula CI 310",
  },
  {
    id: "ci-309",
    location: "CI 309",
    type: "classroom",
    description: "Sala de aula CI 309",
  },
  {
    id: "ci-308",
    location: "CI 308",
    type: "classroom",
    description: "Sala de aula CI 308",
  },
  {
    id: "ci-307",
    location: "CI 307",
    type: "classroom",
    description: "Sala de aula CI 307",
  },
  {
    id: "ci-306",
    location: "CI 306",
    type: "classroom",
    description: "Sala de aula CI 306",
  },
  {
    id: "ci-305",
    location: "CI 305",
    type: "lab-research",
    description: "Laboratório de Pesquisa",
    labs: ["pet"],
  },
  {
    id: "ci-304",
    location: "CI 304",
    type: "classroom",
    description: "Sala de aula CI 304",
  },
];
