import type { Professor } from "../types";

export const professors: Professor[] = [
  {
    id: "adriana-carla-damasceno",
    name: "Adriana Carla Damasceno",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1542344",
    image: "./professor-images/adriana-carla-damasceno.jpg",
  },
  {
    id: "alan-kelon-oliveira-de-moraes",
    name: "Alan Kelon Oliveira de Moraes",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2580083",
    image: "./professor-images/alan-kelon-oliveira-de-moraes.jpg",
  },
  {
    id: "alisson-vasconcelos-de-brito",
    name: "Alisson Vasconcelos de Brito",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2579537",
    image: "./professor-images/alisson-vasconcelos-de-brito.jpg",
  },
  {
    id: "alvaro-francisco-de-castro-medeiros",
    name: "Alvaro Francisco de Castro Medeiros",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1121076",
    image: "./professor-images/alvaro-francisco-de-castro-medeiros.jpg",
    room: "CI 215",
  },
  {
    id: "ana-paula-pintado-wyse",
    name: "Ana Paula Pintado Wyse",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1545785",
    image: "./professor-images/ana-paula-pintado-wyse.jpg",
    room: "CI 203",
  },
  {
    id: "anand-subramanian",
    name: "Anand Subramanian",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1859144",
    image: "./professor-images/anand-subramanian.jpg",
    room: "CI 217",
  },
  {
    id: "andrea-vanessa-rocha",
    name: "Andrea Vanessa Rocha",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1455894",
    image: "./professor-images/andrea-vanessa-rocha.jpg",
  },
  {
    id: "andrei-de-araujo-formiga",
    name: "Andrei de Araujo Formiga",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2798885",
    image: "./professor-images/andrei-de-araujo-formiga.jpg",
    room: "CI 204",
  },
  {
    id: "antonio-jose-boness-dos-santos",
    name: "Antonio Jose Boness dos Santos",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1765608",
    image: "./professor-images/antonio-jose-boness-dos-santos.jpg",
    room: "CI 203",
  },
  {
    id: "luciano-sales-barros",
    name: "Luciano Sales Barros",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1597497",
    image: "./professor-images/luciano-sales-barros.jpg",
    room: "CI 201",
  },
  {
    id: "aparecido-jesuino-de-souza",
    name: "Aparecido Jesuino de Souza",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=6335045",
    image: "./professor-images/aparecido-jesuino-de-souza.jpg",
    room: "CI 222",
  },
  {
    id: "bruno-jefferson-de-sousa-pessoa",
    name: "Bruno Jefferson de Sousa Pessoa",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1893777",
    image: "./professor-images/bruno-jefferson-de-sousa-pessoa.jpg",
    room: "CI 223",
  },
  {
    id: "bruno-petrato-bruck",
    name: "Bruno Petrato Bruck",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=3048216",
    image: "./professor-images/bruno-petrato-bruck.jpg",
    room: "CI 214",
  },
  {
    id: "camila-mara-vital-barros",
    name: "Camila Mara Vital Barros",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1652514",
    image: "./professor-images/camila-mara-vital-barros.jpg",
    room: "CI 201",
  },
  {
    id: "carlos-alberto-nunes-machado",
    name: "Carlos Alberto Nunes Machado",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=6333096",
    image: "./professor-images/carlos-alberto-nunes-machado.jpg",
    room: "CI 221",
  },
  {
    id: "carlos-eduardo-coelho-freire-batista",
    name: "Carlos Eduardo Coelho Freire Batista",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1545948",
    image: "./professor-images/carlos-eduardo-coelho-freire-batista.jpg",
    room: "CI 225",
  },
  {
    id: "christian-azambuja-pagot",
    name: "Christian Azambuja Pagot",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1931204",
    image: "./professor-images/christian-azambuja-pagot.jpg",
  },
  {
    id: "clauirton-de-albuquerque-siebra",
    name: "Clauirton de Albuquerque Siebra",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1723491",
    image: "./professor-images/clauirton-de-albuquerque-siebra.jpg",
    room: "CI 206",
  },
  {
    id: "daniela-coelho-batista-guedes-pereira",
    name: "Daniela Coelho Batista Guedes Pereira",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2300797",
    image: "./professor-images/daniela-coelho-batista-guedes-pereira.jpg",
    room: "CI 202",
  },
  {
    id: "danielle-rousy-dias-ricarte",
    name: "Danielle Rousy Dias Ricarte",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1095991",
    image: "./professor-images/danielle-rousy-dias-ricarte.jpg",
    room: "CI 226",
  },
  {
    id: "derzu-omaia",
    name: "Derzu Omaia",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1934723",
    image: "./professor-images/derzu-omaia.jpg",
    room: "CI 224",
  },
  {
    id: "ed-porto-bezerra",
    name: "Ed Porto Bezerra",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=401182",
    image: "./professor-images/ed-porto-bezerra.jpg",
    room: "CI 213",
  },
  {
    id: "elizabet-maria-spohr-de-medeiros",
    name: "Elizabet Maria Spohr de Medeiros",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2115810",
    image: "./professor-images/elizabet-maria-spohr-de-medeiros.jpg",
    room: "CI 215",
  },
  {
    id: "eudisley-gomes-dos-anjos",
    name: "Eudisley Gomes dos Anjos",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1971919",
    image: "./professor-images/eudisley-gomes-dos-anjos.jpg",
  },
  {
    id: "ewerton-monteiro-salvador",
    name: "Ewerton Monteiro Salvador",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1417704",
    image: "./professor-images/ewerton-monteiro-salvador.jpg",
  },
  {
    id: "felipe-antonio-garcia-moreno",
    name: "Felipe Antonio Garcia Moreno",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1973710",
    image: "./professor-images/felipe-antonio-garcia-moreno.jpg",
    room: "CI 218",
  },
  {
    id: "fernando-menezes-matos",
    name: "Fernando Menezes Matos",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1887274",
    image: "./professor-images/fernando-menezes-matos.jpg",
    room: "CI 226",
  },
  {
    id: "francisco-de-assis-coutinho-souto",
    name: "Francisco de Assis Coutinho Souto",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=337432",
    image: "./professor-images/francisco-de-assis-coutinho-souto.jpg",
    room: "CI 206",
  },
  {
    id: "gilberto-farias-de-sousa-filho",
    name: "Gilberto Farias de Sousa Filho",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2551745",
    image: "./professor-images/gilberto-farias-de-sousa-filho.jpg",
    room: "CI 223",
  },
  {
    id: "giorgia-de-oliveira-mattos",
    name: "Giorgia de Oliveira Mattos",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1192539",
    image: "./professor-images/giorgia-de-oliveira-mattos.jpg",
    room: "CI 227",
  },
  {
    id: "gledson-elias-da-silveira",
    name: "Gledson Elias da Silveira",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1170572",
    image: "./professor-images/gledson-elias-da-silveira.jpg",
    room: "CI 220",
  },
  {
    id: "guido-lemos-de-souza-filho",
    name: "Guido Lemos de Souza Filho",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1149359",
    image: "./professor-images/guido-lemos-de-souza-filho.jpg",
  },
  {
    id: "gustavo-charles-peixoto-de-oliveira",
    name: "Gustavo Charles Peixoto de Oliveira",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2344244",
    image: "./professor-images/gustavo-charles-peixoto-de-oliveira.jpg",
    room: "CI 208",
  },
  {
    id: "gustavo-henrique-matos-bezerra-motta",
    name: "Gustavo Henrique Matos Bezerra Motta",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2126491",
    image: "./professor-images/gustavo-henrique-matos-bezerra-motta.jpg",
    room: "CI 220",
  },
  {
    id: "henrique",
    name: "Henrique",
    room: "CI 219",
  },
  {
    id: "hamilton-soares-da-silva",
    name: "Hamilton Soares da Silva",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=336727",
    image: "./professor-images/hamilton-soares-da-silva.jpg",
  },
  {
    id: "hugo-leonardo-davi-de-souza-cavalcante",
    name: "Hugo Leonardo Davi de Souza Cavalcante",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1298679",
    image: "./professor-images/hugo-leonardo-davi-de-souza-cavalcante.jpg",
    room: "CI 224",
  },
  {
    id: "iguatemi-eduardo-da-fonseca",
    name: "Iguatemi Eduardo da Fonseca",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1545175",
    image: "./professor-images/iguatemi-eduardo-da-fonseca.jpg",
    room: "CI 217",
  },
  {
    id: "jairo-rocha-de-faria",
    name: "Jairo Rocha de Faria",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1565613",
    image: "./professor-images/jairo-rocha-de-faria.jpg",
    room: "CI 207",
  },
  {
    id: "jan-sokolowski",
    name: "Jan Sokolowski",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=3080519",
    image: "./professor-images/jan-sokolowski.jpg",
  },
  {
    id: "jose-antonio-gomes-de-lima",
    name: "Jose Antonio Gomes de Lima",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=337324",
    image: "./professor-images/jose-antonio-gomes-de-lima.jpg",
    room: "CI 221",
  },
  {
    id: "jose-miguel-aroztegui-massera",
    name: "Jose Miguel Aroztegui Massera",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1936480",
    image: "./professor-images/jose-miguel-aroztegui-massera.jpg",
    room: "CI 216",
  },
  {
    id: "josilene-aires-moreira",
    name: "Josilene Aires Moreira",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1448867",
    image: "./professor-images/josilene-aires-moreira.jpg",
    room: "CI 227",
  },
  {
    id: "kely-diana-villacorta-villacorta",
    name: "Kely Diana Villacorta Villacorta",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1939266",
    image: "./professor-images/kely-diana-villacorta-villacorta.jpg",
    room: "CI 218",
  },
  {
    id: "leandro-carlos-de-souza",
    name: "Leandro Carlos de Souza",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1140339",
    image: "./professor-images/leandro-carlos-de-souza.jpg",
    room: "CI 225",
  },
  {
    id: "leonardo-vidal-batista",
    name: "Leonardo Vidal Batista",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1167863",
    image: "./professor-images/leonardo-vidal-batista.jpg",
    room: "CI 224",
  },
  {
    id: "liliane-dos-santos-machado",
    name: "Liliane dos Santos Machado",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2379027",
    image: "./professor-images/liliane-dos-santos-machado.jpg",
    room: "CI 213",
  },
  {
    id: "lincoln-david-nery-e-silva",
    name: "Lincoln David Nery e Silva",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2476422",
    image: "./professor-images/lincoln-david-nery-e-silva.jpg",
    room: "CI 211",
  },
  {
    id: "lucidio-dos-anjos-formiga-cabral",
    name: "Lucidio dos Anjos Formiga Cabral",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1175878",
    image: "./professor-images/lucidio-dos-anjos-formiga-cabral.jpg",
    room: "CI 223",
  },
  {
    id: "marcelo-yuri",
    name: "Marcelo Yuri",
    room: "CI 226",
  },
  {
    id: "mardson-freitas-de-amorim",
    name: "Mardson Freitas de Amorim",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1122252",
    image: "./professor-images/mardson-freitas-de-amorim.jpg",
    room: "CI 219",
  },
  {
    id: "moises-dantas-dos-santos",
    name: "Moises Dantas dos Santos",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1559497",
    image: "./professor-images/moises-dantas-dos-santos.jpg",
    room: "CI 222",
  },
  {
    id: "natasha-correia-queiroz-lino",
    name: "Natasha Correia Queiroz Lino",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2636257",
    image: "./professor-images/natasha-correia-queiroz-lino.jpg",
    room: "CI 220",
  },
  {
    id: "raimundo",
    name: "Raimundo",
    room: "CI 209",
  },
  {
    id: "raoni-kulesza",
    name: "Raoni Kulesza",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2777570",
    image: "./professor-images/raoni-kulesza.jpg",
    room: "CI 212",
  },
  {
    id: "roberto-quirino-do-nascimento",
    name: "Roberto Quirino do Nascimento",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=337293",
    image: "./professor-images/roberto-quirino-do-nascimento.jpg",
    room: "CI 222",
  },
  {
    id: "rostand",
    name: "Rostand",
    room: "CI 212",
  },
  {
    id: "ruy-alberto-pisani-altafim",
    name: "Ruy Alberto Pisani Altafim",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1971934",
    image: "./professor-images/ruy-alberto-pisani-altafim.jpg",
    room: "CI 219",
  },
  {
    id: "sergio-de-carvalho-bezerra",
    name: "Sergio de Carvalho Bezerra",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1363532",
    image: "./professor-images/sergio-de-carvalho-bezerra.jpg",
    room: "CI 207",
  },
  {
    id: "tatiana-araujo-simoes",
    name: "Tatiana Araujo Simoes",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2486912",
    image: "./professor-images/tatiana-araujo-simoes.jpg",
    room: "CI 208",
  },
  {
    id: "teobaldo-leite-bulhoes-junior",
    name: "Teobaldo Leite Bulhões Junior",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1058696",
    image: "./professor-images/teobaldo-leite-bulhoes-junior.jpg",
    room: "CI 205",
  },
  {
    id: "tiago-pereira-do-nascimento",
    name: "Tiago Pereira do Nascimento",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2042972",
    image: "./professor-images/tiago-pereira-do-nascimento.jpg",
  },
  {
    id: "thais-gaudencio-do-rego",
    name: "Thais Gaudencio do Rego",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1743917",
    image: "./professor-images/thais-gaudencio-do-rego.jpg",
    room: "CI 202",
  },
  {
    id: "tiago-maritan-ugulino-de-araujo",
    name: "Tiago Maritan Ugulino de Araujo",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2813926",
    image: "./professor-images/tiago-maritan-ugulino-de-araujo.jpg",
  },
  {
    id: "valdecir-becker",
    name: "Valdecir Becker",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1456438",
    image: "./professor-images/valdecir-becker.jpg",
    room: "CI 225",
  },
  {
    id: "vivek-nigam",
    name: "Vivek Nigam",
    department: "Departamento de Sistemas de Computação",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1971457",
    image: "./professor-images/vivek-nigam.jpg",
  },
  {
    id: "vitor-meneghetti-ugulino-de-araujo",
    name: "Vitor Meneghetti Ugulino de Araujo",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1981734",
    image: "./professor-images/vitor-meneghetti-ugulino-de-araujo.jpg",
    room: "CI 221",
  },
  {
    id: "yuska-paola-costa-aguiar",
    name: "Yuska Paola Costa Aguiar",
    department: "Departamento de Informática",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=2023253",
    image: "./professor-images/yuska-paola-costa-aguiar.jpg",
    room: "CI 211",
  },
  {
    id: "yuri-de-almeida-malheiros-barbosa",
    name: "Yuri de Almeida Malheiros Barbosa",
    department: "Departamento de Computação Científica",
    sigaa: "https://sigaa.ufpb.br/sigaa/public/docente/portal.jsf?siape=1827772",
    image: "./professor-images/yuri-de-almeida-malheiros-barbosa.jpg",
  },
  {
    id: "mcc-meninas-na-ciencia-da-computacao",
    name: "MCC - Meninas na Ciência da Computação",
    department: "Projeto de Extensão",
    room: "CI 227",
  },
];
